### ISSUE TITLE
Failed to locate resource in classpath

### ISSUE THREAD

**Issue by sideeffffect** [scalafx/scalafx-ensemble#21]
when I try to run `Ensemble`, I'm getting the `Failed to locate resource in classpath: /scalafx/ensemble/example/example.tree` exception; in [EnsembleTree](https://github.com/scalafx/scalafx-ensemble/blob/1e24181/src/main/scala/scalafx/ensemble/EnsembleTree.scala#L68)
most likely caused by the commit https://github.com/scalafx/scalafx-ensemble/commit/1e24181e1a18d19abd9abca40e25092e8d013299

**Comment by jpsacha** [comment]
How do you run `Ensemble`?
It runs fine in SBT and IDEA.

**Comment by sideeffffect** [comment]
I get this error when I run it in IDEA
is there any way I can be of any help with debuging this issue?
btw I have OpenJDK 8

**Comment by jpsacha** [comment]
It would be great if you could help. 
What OS are you using?
Can you try using SBT command `run`? You can do it from Terminal prompt in IDEA.

**Comment by sideeffffect** [comment]
`sbt run` works OK. and now even running from IDEA works OK too.
I cloned a fresh `scalafx-ensemble` and tried running it from IDEA but with the same error.

So it seems that you have to run `sbt run` at least once to be able to start `scalafx-ensemble` from IDEA.
(that wan't necessary before the https://github.com/scalafx/scalafx-ensemble/commit/1e24181e1a18d19abd9abca40e25092e8d013299 commit)

**Comment by dmolesUC3** [comment]
I get the same issue, running the `Ensemble` class directly from IDEA (15.0.4 on Mac OS 10.10.5). I guess `example.tree` is generated by SBT? It doesn't exist in the source, but appears under `target` after `sbt run`.

**Comment by jpsacha** [comment]
Before Ensemble main method is run the resources need to be generated. The safest way to run Ensemble in IDEA is to create a run configuration for SBT task `run`, then resources are generated correctly.
