### ISSUE TITLE
Windows 10: jdkPackager:packageBin = build error, missing ant-javafx.jar

### ISSUE THREAD

**Issue by ScalaWilliam** [scalafx/scalafx-ensemble#24]
Hello,

I tried to package up this project on Windows with JDK 11, and got this error:
```
[error] (JdkPackager / antBuildDefn) Please set key `antPackagerTasks in JDKPackager` to `ant-javafx.jar` path, which should be found in the `lib` directory of the Oracle JDK 8 installation. For example (Windows):
[error] (antPackagerTasks in JDKPackager) := Some(file("C:\\Program Files\\Java\\jdk1.8.0_45\\lib\\ant-javafx.jar"))
[error] Total time: 22 s, completed Oct 26, 2019, 10:45:54 PM
```
I am <a href="https://stackoverflow.com/questions/54591725/ant-tasks-definitions-openjdk-11-javafx-sdk-11-eclipse-2018-12">told</a> that it doesn't exist in Java 11.

How do you make it work?

Thank you :-)

**Comment by jpsacha** [comment]
javapackager was removed from JDK11 and, as I understand, there is no official replacement. There maybe some way to make it work with the new version of javapackager (https://mail.openjdk.java.net/pipermail/openjfx-dev/2018-September/022500.html). Maybe future versions of Java will bring it back.

Note that there is a good commercial tool [Install4j](https://www.ej-technologies.com/products/install4j/overview.html) that works very well for building installers for JDK, Scala, etc.

**Comment by jpsacha** [comment]
Due to lack of support from JDK11+, sbt-native-packager setup will be removed, see issue #26. if future versions of JDK will bring back jdkPackager, we will get back to it.
