### ISSUE TITLE
broken samples

### ISSUE THREAD

**Issue by danielbe1** [scalafx/scalafx-ensemble#29]
I've installed the packaged binary for both mac and windows (v.1.14.0), some of the samples are broken both in the application and in the saved project, namely: 
- Accordion - Nothing happens on when clicking any of the panes.
- Tree View - The nodes do not expand or show children when first opening the sample, sometimes switching to the source tab fixes this.

**Comment by jpsacha** [comment]
There is a bug in Accordion example. Inside each `TitledPane` it should be `content` not `children`. There is also some layout issue related to embedding in Ensemble window. You need to resize window to see content of the TitledPane.

Example code in TreeView seems fine (runs correctly on its own), but have the same layout problem, need to resize the window to make it work.

At this point do do not know yet what is causing the layout issues.

**Comment by jpsacha** [comment]
I updated the Ensemble code to update layout after a sample was switched b8a560a
