### ISSUE TITLE
Cloned with InteliJ exception on start

### ISSUE THREAD

**Issue by udsl** [scalafx/scalafx-ensemble#30]
On Mac Big Sur, IntelliJ Utilmate up-to-date plugins, Scala 2.13 tried with JDK 11 and 15.

Get error on startup, new to Scala so no idea how to proceed

Exception in Application start method
java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: requirement failed: Failed to locate resource in classpath: /scalafx/ensemble/example/example.tree
	at scala.Predef$.require(Predef.scala:338)

**Comment by jpsacha** [comment]
The resource file `/scalafx/ensemble/example/example.tree` needs to be generated before the Ensemble application starts. The steps to do that are described in the [README]()

Basically, the generation is done by custom SBT task defined in [build.sbt](https://github.com/scalafx/scalafx-ensemble/blob/d79a854742f69456c87f9ebf9f362a93fe4af8d7/build.sbt#L45). In SBT build it is executed automatically. Unfortunately IntelliJ does not use SBT to generate resources by default. There several ways to address it, one in described in the README section [Compile and Run using Intellij IDEA](https://github.com/scalafx/scalafx-ensemble/blob/master/README.md#compile-and-run-using-intellij-idea). Another way, maybe simpler, it to tell IntelliJ to use SBT for build. Go to "sbt Settings", under "sbt shell" select box next to "builds", see example below

![image](https://user-images.githubusercontent.com/1205408/110989114-670cc300-833f-11eb-9766-401b98e8c9a5.png)
